### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by akidox** [electron/electron-quick-start#124]
the `npm install` process stops at the line `node install.js`.
node -v 6.9.4, npm -v 4.1.1
no error thrown.
Operating system macOS sierra 10.12.2

**Comment by efmeniz** [comment]
Same error

$ node -v
v7.4.0
$ npm -v
4.0.5
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**Comment by zz-zhangzhao** [comment]
@efmeniz @akidox  I met the same error.
add this in your `~/.npmrc`

```
electron_mirror="https://npm.taobao.org/mirrors/electron/"
```

to install electron with the taobao mirror. it worked for me.

**Comment by akidox** [comment]
but there is no such a file in my root directory. @zz-zhangzhao

**Comment by cpruijsen** [comment]
npm i worked just now without errors my end fwiw

**Comment by akidox** [comment]
It turns out to be a network issue. I used a proxy tool over Terminal and run `npm install electron --verbose` ( `--verbose` tells you where the progress stops and since the electron is the only dependency of the project), and the installation succeed.

**Comment by cpruijsen** [comment]
why was this re-opened? (the installation succeeded?)

**Comment by akidox** [comment]
I thought others may want to leave a comment before they can solve the problem. you are right.

**Comment by zz-zhangzhao** [comment]
@akidox 
Sorry to reply to some of the late, because of the reasons for the Great Firewall in China. The speed of installing npm modules is slow, in which case a solution is to use the domestic mirrors to accelerate, taobao mirror is one of them.

Taobao mirror contains all of the npm modules. To use it, you should create a new file at your OSX home directory and named `.npmrc` with the configuration items in it. you can get more details at 
[https://docs.npmjs.com/files/npmrc](https://docs.npmjs.com/files/npmrc)

Similarly, to install the electron with taobao mirror In order to speed up the installation in China, you can add `electron_mirror="https://npm.taobao.org/mirrors/electron/"` in your `~/.npmrc` .

Sorry for my poor English. I hope this could help you a little.

**Comment by akidox** [comment]
@loatheb Thanks a lot.

**Comment by PleaseTryAgain** [comment]
this is all because npm install not success, I use` cnpm (taobao mirror) install` successed. it takes long time to solve it . I read a lot of issues but not work for me  ,now it works . tks @loatheb.
