### ISSUE TITLE
npm-elifecycle-error

### ISSUE THREAD

**Issue by LakshminarayananG** [electron/electron-quick-start#174]
Hello..
I am working on test automation project developed using node js. When running the test from the repository with the 'npm run android' command, getting the error attached.

can someone please assist. Been stuck with this for the last couple of days.
<img width="1440" alt="screen shot 2017-11-10 at 5 24 14 pm" src="https://user-images.githubusercontent.com/29523140/32661660-c5cf3a92-c64d-11e7-9e58-20aadbd198a7.png">

<img width="1440" alt="screen shot 2017-11-10 at 5 24 00 pm" src="https://user-images.githubusercontent.com/29523140/32661688-eecbe666-c64d-11e7-95ec-2e4b8e81d4dd.png">

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

We are sorry that we do not always have the capacity to look at all reported issues in a timely manner. There have been many changes in Electron since this issue was reported and it may have been fixed in that time.

It's not clear what version of Electron this was tested with; however, the latest version now is 1.8.3 and that is the version that should be used by a fresh `git clone` of electron-quick-start. It would help us greatly if you could test this issue with the latest version. If the problem persists, please attach the relevant logs rather than screenshots.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.
