### ISSUE TITLE
Cannot find module './internal/withoutIndex'

### ISSUE THREAD

**Issue by ccpwcn** [electron/electron-quick-start#214]
I can't find any description of this error on Google. What's wrong with this error?
![tim 20180701114903](https://user-images.githubusercontent.com/5465756/42130882-0e530c10-7d25-11e8-8303-98020f4c2a95.jpg)

**Comment by codebytere** [comment]
@ccpwcn please describe what you did prior to seeing that error, including but not limited to:
1) Steps taken to run the applicaton
2) Operating System and version
3) Electron version
4) Troubleshooting attempts

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@ccpwcn if you're looking for general support about building Electron  apps I'd recommend the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
