### ISSUE TITLE
BUG: broken template ~ Electron v5.0.0+ causes complete failure of application unless `--no-sandbox` is used

### ISSUE THREAD

**Issue by rivy** [electron/electron-quick-start#278]
`npm start` fails when running the electron application when using the LTS version of node (currently v10.15.3).

Downgrading electron to v4 corrects the problem.

If a later version of node is needed, a prompt to that effect would be nice. And providing a recipe to get this quickstart working with the current LTS version of node would likely be quite beneficial to those starting out with electron.

**Comment by pathim** [comment]
The simplest way to fix the issue is to append "--no-sandbox" to the "start" script entry in package.json:

`"scripts": {
    "start": "electron --no-sandbox ."
  },`

This is related to [this](https://github.com/electron/electron/issues/15760) breaking change in electron.
I am new to electron as well but I am not sure if this is a useful workaround or if the no-sandbox-mode will be deprecated.

Another way is to enable unprivileged user namespaces by doing
`sysctl kernel.unprivileged_userns_clone=1`
as root.

And a third way is to set `node_modules/electron/dist/chrome-sandbox` SUID root. But this really doesn't sit well with me since giving root privileges to arbitrary applications just seems wrong.

**Comment by thierer** [comment]
electron/electron#17972 provides a bit more background

**Comment by rivy** [comment]
So, six months later ... reading the relevant issues leads me to believe that `--no-sandbox` is going to be widely required to run any electron application now, unless you want to give `sudo` access to every electron application installation process (which sounds like incredibly poor practice).

Any chance that someone in the `electron` dev group will tackle this with an explanation/documentation of the issue, how to use it or work around it, and ultimately fix this repository to actually run correctly?

The main electron page recommends this as a beginner starting point ... and it's been broken for 6+ months. That's very bad on-boarding.

**Comment by rivy** [comment]
# ⚰️

**Comment by vladimiry** [comment]
> --no-sandbox is going to be widely required to run any electron application now

`--no-sandbox` only presumably required for the containerized Linux packages, like AppImage and Snap. For regular deb, pacman, rpm, etc packages there is a SUID sandbox fallback option that kicks in if user namespace feature is disabled in the system. For SUID sandbox fallback work properly the `chrome-sandbox` binary needs to be slightly processed as a part of the bundling process.

So the solution is to tweak the bundling process of your electron program: 
- hardcode `--no-sandbox` arg into the AppImage/Snap like packages
- preprocess the `chrome-sandbox` for other packages types.

So it's quite possible to prepare any Linux package with the electron-based program and there will be no need for any extra action from the end-users (like running `sudo sysctl kernel.unprivileged_userns_clone=1` or manually tweaking the `chrome-sandbox` binary).
