### ISSUE TITLE
What is the bare bones size of an Electron source project and target application?

### ISSUE THREAD

**Issue by velara3** [electron/electron-quick-start#284]
The project here is very small but when I added the dependencies the project weighs in at about 150MB. 

1. Can I delete some or all items in the node_modules folder? I eventually need to call a native process but that's about it
2. Is exported application much smaller? 

The reason for reducing the project size is that: 
- it may end up in version control. i do not want 150mb of common files
- i might work on this project with others so sharing it as a getting started project (so small project size is important)
- creating an exported application with only the necessary libraries (small application)

**Comment by epreston** [comment]
You should exclude the "node_modules" folder from source control and check in your "package-lock.json".  (see ".gitignore")   This way, you don't check in the dependancies, everyone loads them by doing a "npm install" or "yarn install" and you know that everyone has the same dependancy files.  

Have a standing agreement that people don't do a "npm update" unless they are working on updating dependancies for the project and everyone using it.

**Comment by epreston** [comment]
Your "package.json" may contain different sets of dependancy definitions.  One for development systems with extra tooling and ones for production / integration testing.  This way, developers can test and switch between debug and non debug libraries and builds.

Also, don't include your builds in the source repository.  Archive them out separately.  You will meet all of your goals.

**Comment by codebytere** [comment]
Closing in agreement with the above!

**Comment by velara3** [comment]
@codebytere I didn't get an answer for this. I will add more details: 

1. Can I delete some or all items in the node_modules folder? I eventually need to call a native process but that's about it.
2. Is exported application much smaller than the size of the project?

**Comment by epreston** [comment]
Common question and it confused me at first when I was starting with node.

The items in the "node_modules" folder may or may not find their way into the final app.  Some of them are needed to build your product, some are needed to test it, others are dependancies for the running app.  Think of it as working materials, not the final materials.  Check your "package.json" to understand what will be boiled down for prod.  

Remember, some tooling and example projects are already setup to remove things which are not actively used when the dependancies are bundled into the final application distributable.  Often, it is more work to force the tools to include something that is not explicitly needed.  (for instance you are dynamically pulling things in at run time).  Short answer, you are getting what you want.

Yes, the exported application is vastly smaller.

Another thing to note is, you don't want to put these "working materials" into source code control.  Often when they install, they setup everything they need to operate on the target development system.  It sometimes works if you just copy the files over, but, you will run into issues because the people maintaining the dependancies assume you are installing them normally when needed.

The analogy that I can think of is this: destroying your cookie cutter does not make the cookies smaller.  It is necessary for making the cookies, but not part of the final cookie.  It should be the same for everyone to maintain consistency.  Some attributes of the cooky cutter will be in the final cookie. (I don't know if this helps or I need to take my lunch break)
