### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined     at HTMLButtonElement.<anonymous> 

### ISSUE THREAD

**Issue by darshan-kndr** [electron/electron-quick-start#287]
facing above error , my code is
--------------------------------------------------------------------------------
console.log("rederer process 2");

const BrowserWindow = require('electron').remote.BrowserWindow
const electron = require('electron')
const app = electron.app
const url = require('url')
const path = require('path')

let win3
const newWindowBtn = document.getElementById('countbtn')
newWindowBtn.addEventListener('click', function (event) {

    try {  
            app.on('ready', () => {
            let displays = electron.screen.getAllDisplays()
            let externalDisplay = displays.find((display) => {
                return display.bounds.x !== 0 || display.bounds.y !== 0
            })

            if(externalDisplay){
            win3 = new BrowserWindow({
                width: 1024, height: 768, backgroundColor: '#000000', frame: false,
                x: externalDisplay.bounds.x + 50,
                y: externalDisplay.bounds.y + 50
            })
            win3.loadURL(url.format({
                pathname: path.join(__dirname, 'index3.html'),
                protocol: 'file:',
                slashes: true
            }))
        }
        })        
    }
    catch (e) {
        console.log(e)
    }
})

**Comment by codebytere** [comment]
The structure of this application is not clear, especially with regard to which processes you're running these files in, what you're including, etc. Without this information, we cannot triage this effectively. for the above reasons i'm setting this issue as `blocked` and will be closed in 10 days.

If this issue is made clearer and more reproducible before that time, we will continue to investigate its cause.

**Comment by darshan-kndr** [comment]
Thank you. I found the solution.
