### ISSUE TITLE
electron开发win桌面应用弹框样式问题

### ISSUE THREAD

**Issue by mhsgit** [electron/electron-quick-start#303]
怎么修改alert、confirm等弹框的默认标题，标题一直是Electron，很不友好，希望有大神帮助，怎么修改。

**Comment by codebytere** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by mhsgit** [comment]
Thanks
