### ISSUE TITLE
翻了两个来小时也没找到哪里修改默认桌面图标的

### ISSUE THREAD

**Issue by myerwang** [electron/electron-quick-start#349]
新手党真是头疼，快速演示里最关键的部分不能说明一下么

**Comment by codebytere** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
