### ISSUE TITLE
no installation progress using npm install -g @angular/cli@latest and stucks at

### ISSUE THREAD

**Issue by anjaikr** [electron/electron-quick-start#398]
no installation progress using npm install -g @angular/cli@latest and stucks at 
**npm install [ .....] \ postinstall: sill install executeActions**
Please help, I am not able to install latest Angular CLI, I have already installed latest version of Nodejs on Windows 10 Pro machine

_Originally posted by @anjaikr in https://github.com/electron/electron-quick-start/issues/127#issuecomment-652592279_

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by zerozin-kang** [comment]
Did you fix this problem? I haven't been able to implement it for several days due to the same problem. I tested it on another computer, and it's all working fine.
