### ISSUE TITLE
npm start don't work.

### ISSUE THREAD

**Issue by aiivy782** [electron/electron-quick-start#431]
I want to start Electron quick start. Whenever I enter `npm start` in PowerShell, I get an error like this: 
![Снимок экрана (22)](https://user-images.githubusercontent.com/46345948/97107219-731d1e80-16d7-11eb-8c30-e2c951e4576b.png)

**Comment by erickzhao** [comment]
Hey @aiivy782, from the error message, it seems like you somehow got `electron-prebuilt` in your dependencies? This hasn't been in the deps since 2016 (see #79). `whenReady` was introduced in Electron 3, and it seems like you're using an older version.

Did you just recently clone this repository? What does your `package.json` look like?

**Comment by aiivy782** [comment]
I clone the repository one week ago. And I can't find my ```package.json``` file.

**Comment by erickzhao** [comment]
@aiivy782 If you don't have a `package.json` file, something seems to be wrong on your end. `package.json` should be in the root directory of your local copy of this repository.

**Comment by aiivy782** [comment]
Hey there! You can close this issue. I install Electron Fiddle and all work correctly.
