### ISSUE TITLE
electron package issue

### ISSUE THREAD

**Issue by caishengmao** [electron/electron-quick-start#65]
Electron - quick - start in the macBook Pro package, package, how to change the default application icon in the json file.Worried, help to prompt, thank you very much.

**Comment by jlord** [comment]
I'm not sure what your question is? This Quick Start doesn't include packaging setup. 

You can [set your app's icon](http://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions) in the `BrowserWindow` and when [using the `icon` option](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon) in `electron-packager`. Hope that helps.

**Comment by herbertpimentel** [comment]
It is my very first time here and I was following the quick-start tutorial looking for a sample that shows me how to  build an app that could run on Windows, Linux and Mac. 

but instead of it, I got confused because the documentation says:

> To distribute your app with Electron, the folder containing your app should be named app and placed under Electron’s resources directory (on macOS it is Electron.app/Contents/Resources/ and on Linux and Windows it is resources/) On Windows and Linux: electron/resources/app


Only after have built the app, the documentation says that I need change the name of my project folder to "app" and put it on this electron path to be able to build it. by the way, where is this electron path the documentation talks about?  

So, I belive that quick-start tutorial must be changed to include information about how to pack it making the entire process more clear to those that are following quick-start tutorial.

**Comment by jlord** [comment]
Feel free to re-open with more information later 👍
