### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by yuxink** [electron/electron-quick-start#888]
PS C:\Users\yxu7szh\Projects\electron-quick-start> npm install
npm ERR! code 1
npm ERR! path C:\Users\yxu7szh\Projects\electron-quick-start\node_modules\electron
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! RequestError: getaddrinfo ENOTFOUND github.com
npm ERR!     at ClientRequest.<anonymous> (C:\Users\yxu7szh\Projects\electron-quick-start\node_modules\got\dist\source\core\index.js:970:111)
npm ERR!     at Object.onceWrapper (node:events:640:26)
npm ERR!     at ClientRequest.emit (node:events:532:35)
npm ERR!     at ClientRequest.origin.emit (C:\Users\yxu7szh\Projects\electron-quick-start\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:442:9)
npm ERR!     at TLSSocket.emit (node:events:520:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR!     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
