### ISSUE TITLE
electron not found

### ISSUE THREAD

**Issue by noname29** [electron/electron-quick-start#889]
I am using centos on Oracle's vm and I used ```npm install electron -g``` to install electron on centOS

```
[root@ilk testcases]# electron main.js 
/usr/lib/node_modules/electron/dist/electron: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

```

I get this error above. I found some solutions that offer installation of packages with ```apt install``` yet my system uses ```yum install```

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
