### ISSUE TITLE
The project successfully starts and displays the interface, but it crashes shortly afterward.

### ISSUE THREAD

**Issue by listenecho** [electron/electron-quick-start#905]
[24044:0429/160705.581:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
Done in 4.23s.

platform：windows

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
