### ISSUE TITLE
yarn install exit code :1

### ISSUE THREAD

**Issue by LEI-LJ** [electron/electron-quick-start#914]
![image](https://github.com/electron/electron-quick-start/assets/110337030/8e234584-c2ec-4cab-a237-4e7f055ef2da)
I've dealt with it many times and I haven't found anything. In my experience this is a very simple question, and I hope to get an answer !

**Comment by LEI-LJ** [comment]
my nodejs version is v18.20.3

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
