### ISSUE TITLE
quick start app `npm install` fails

### ISSUE THREAD

**Issue by tonygaetani** [electron/electron-quick-start#93]
Following instructions on http://electron.atom.io/
```
# Clone the Quick Start repository
$ git clone https://github.com/electron/electron-quick-start

# Go into the repository
$ cd electron-quick-start

# Install the dependencies and run
$ npm install && npm start
```

I am on Mac OS X El Capitan Version 10.11.6
node version: v6.2.1
npm version: 3.9.3

ouput:
```
% npm install

> electron@1.4.3 postinstall /Users/someone/misc_code/electron-quick-start/node_modules/electron
> node install.js

undefined:1
{=true
 ^

SyntaxError: Unexpected token = in JSON at position 1
    at Object.parse (native)
    at exports.parse (/Users/someone/misc_code/electron-quick-start/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/Users/someone/misc_code/electron-quick-start/node_modules/rc/index.js:31:20)
    at Array.forEach (native)
    at module.exports (/Users/someone/misc_code/electron-quick-start/node_modules/rc/index.js:44:36)
    at Object.<anonymous> (/Users/someone/misc_code/electron-quick-start/node_modules/electron-download/build/index.js:12:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

npm-debug.log: https://gist.github.com/tonygaetani/3c0050ed91f755c0086a578105b6068b

**Comment by tonygaetani** [comment]
my .npmrc was the problem, sorry, closing

**Comment by jmafc** [comment]
I'm having a very similar problem, except I'm on Linux Debian. If I try to install it under the cloned repo with just `npm install`, it fails with the following error:
```
Error: GET https://github.com/electron/electron/releases/download/v1.4.3/electron-v1.4.3-linux-x87.zip returned 404
/usr/local/lib/node_modules/electron/install.js:22
  throw err
  ^
```
And indeed there is no such `download` directory (aside: I don't know where it's getting linux-x87 from). If I try to install either 1.4.3 or 1.4.1 globally with `npm install -g electron@1.4.1` it gives the same error. Npm version is 3.4.0 (node 4.3.1) so I doubt it's because I don't have the latest npm or node.

If I remove/edit my .npmrc, which only has `prefix=/usr/local`, it  first gives the following warning:
```
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
```
and then complains that I don't have access to that directory and that perhaps I should run as root. But I definitely *don't* want to install electron under `/usr/lib/node_modules`, only under `/usr/local/lib/node_modules` like all the other node modules that I have installed there.

Let me know if I should open a separate issue.

**Comment by jmafc** [comment]
I just saw issue #92 and decided to give the global install a try after installing the nodejs-legacy package, but it still fails.

**Comment by MarshallOfSound** [comment]
@jmafc Just uninstall all previous versions of `node` (Your `nodejs` and `nodejs-legacy` packages)

And then install the glorious, wonderful, maginficent, life saving [`nvm`](https://github.com/creationix/nvm)

**Comment by jmafc** [comment]
That doesn't seem to make sense: `nvm` says it's a "bash script to manage multiple active node.js versions", if I uninstall all previous versions of `node` (I only have one--`nodejs-legacy` only creates a symlink), what is `nvm` going to manage? and what will happen when I invoke `node`? Also, when it comes to basic packages like `node`, `python`, etc., I prefer to install the distribution package--which has never given me trouble until I tried to install electron (and I've install lots of other modules).

**Comment by MarshallOfSound** [comment]
@jmafc `nvm` is the best (and most reliable) way I have ever found for installing whatever version of node you need on **any** linux based distro regardless of package manager, flavor or architecture.

I reccomend it because it "Just Works"(TM) and has the added bonus of an easy node version upgrade.  `nodejs` is very fast moving and last time I tried to install it from package managers on debian based systems the node version so far out of date it wasn't even funny.

So all you need to do to get node running properly is run that `nvm` install script. Then

```bash
nvm install 6
nvm use 6
```

NVM handles adding the `node` binaries to your path for you.

**Comment by jmafc** [comment]
@MarshallOfSound Why should I have to install a newer version of node if the one I have works well with all the other modules I use?  Plus, from the error messages there seems to be wrong with the electron distribution, not with node (why does it try to install from a non-existent github url? why is it looking for linux-x87?). So, until someone from electron says otherwise, I'll stick with what I have.

**Comment by MarshallOfSound** [comment]
> Why should I have to install a newer version of node

Because it's always better to be up to date?  Especially when their are basically no breaking changes and a massive performance boost?

> Plus, from the error messages there seems to be wrong with the electron distribution

It is trying to download `x87` because **you're node version** is reporting it's architecture as `x87`.  This is wrong, and it's either a broken `node` install or your computer is on one hell of a funky architecture 😆 

> So, until someone from electron says otherwise, I'll stick with what I have.

I mean, I'm literally just trying to help you but if you want to wait for someone different on the Electron team to tell you something else be my guest.  I can't help people who don't want my help.

**Comment by MarshallOfSound** [comment]
@jmafc Are you possibly running a Quark processor?

**Comment by jmafc** [comment]
Re: Quark. No, it's a Core i5.

Re: performance boost. I hardly ever use node. I was just curious about electron.

**Comment by MarshallOfSound** [comment]
@jmafc Then you somehow have the wrong node installed.  (Don't know how).  But if you run `console.log(require('os').arch())` in node you should see `x87`.  The `x87` build of node.js is for Quark based intel CPU's only.

You need to install the correct version of node for your architecture 👍
