### ISSUE TITLE
electron-quick-start can't start without any sound device

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [electron/electron-quick-start#950]
Hello, 

initially, i found this in min browser (https://github.com/minbrowser/min/issues/2532), but there asked to create ticket here. 
so, i've cloned repo and tried to start:
```
~/electron-quick-start$ npm install

added 72 packages, and audited 73 packages in 16s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
~/electron-quick-start$ npm start

> electron-quick-start@1.0.0 start
> electron .

/home/user/electron-quick-start/node_modules/electron/dist/electron: symbol lookup error: /home/user/electron-quick-start/node_modules/electron/dist/electron: undefined symbol: snd_device_name_get_hint, version ALSA_0.9
```

and doesn't start. 

os: ubuntu 24.04 in WSL

**Comment by yaroslav-nakonechnikov** [comment]
then i found https://github.com/electron/electron-quick-start/issues/486, and here found missing piece:

`sudo apt-get install libasound2t64`
after installing that package it managed to start.

**Comment by mikkorantalainen** [comment]
> `sudo apt-get install libasound2t64`

I think `sudo apt install alsa-oss` is better option because it automatically installs correct packages for larger span of distributions. The package `libasound2t64` wasn't the correct package for older Ubuntu versions but `alsa-oss` package installs correct dependencies for everything since Ubuntu 18.04 LTS or so.
